# -*- mode:Makefile; -*-

ifeq ($(OS),win32)
	PWD=$(subst \,/,$(dir $(lastword $(MAKEFILE_LIST))))
endif

include $(PWD)/../$(BOARD)/Makefile.build

VPATH = ..
SRC = $(foreach dir, $(VPATH), $(wildcard $(dir)/*.c))
OBJ = $(notdir $(SRC:.c=.o))

CFLAGS += -I$(PWD)/../include
MAKEDEPEND += -I$(PWD)/../include

all : output.elf
	$(MAKEBIN)
	$(MAKEHEX)
	@echo "Build done!"

output.elf : $(OBJ)
	$(LD) $(OBJ) -o $@ $(LDFLAGS)

-include $(OBJ:.o=.d)

%.o : %.c
	$(CC) $(CFLAGS) $< -o $@
	$(MAKEDEPEND)
